import React, { useState } from 'react';
import { ArrowUpRight, Award, BookOpen, CheckCircle2, Clock, GraduationCap, Sparkles } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { LEARNING_MODULES } from '../../data/mockData';
import { HelpButton } from '../ui/PageChrome';

export const LearningView: React.FC = () => {
  const { navigateTo, activeRole } = useApp();
  const [completed, setCompleted] = useState<string[]>(LEARNING_MODULES.filter(item => item.status === 'Completed').map(item => item.id));
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 border-b border-slate-200/70 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow"><GraduationCap className="h-3.5 w-3.5" /> Enablement</div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">Learn the signal. <span className="font-serif italic font-normal text-blue-950">Use it well.</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Concise learning paths for {activeRole}. Full course content lives in Atlas; this workspace keeps the decisions, completion state, and next actions close.</p></div><div className="flex items-center gap-2"><HelpButton title="How Learning works" body="Use the cards to open Atlas resources or mark a module complete. Assessment recommendations appear here after a knowledge check." /><button onClick={() => navigateTo('assessments')} className="button-primary"><Award className="h-3.5 w-3.5" /> Take an assessment <ArrowUpRight className="h-3.5 w-3.5" /></button></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Learning modules" value={LEARNING_MODULES.length.toString()} /><Metric label="Marked completed" value={`${completed.length}/${LEARNING_MODULES.length}`} /><Metric label="Next best action" value="Atlas" /></div>
    <div className="grid gap-4 md:grid-cols-2">{LEARNING_MODULES.map(module => { const isDone = completed.includes(module.id); return <article className="premium-card flex flex-col justify-between p-5 transition hover:-translate-y-1" key={module.id}><div><div className="flex items-center justify-between gap-2"><span className="tag tag-blue">{module.area}</span><span className={`tag ${isDone ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-600'}`}>{isDone ? 'Completed' : 'Not completed'}</span></div><h2 className="mt-5 text-lg font-semibold tracking-tight text-slate-950">{module.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{module.summary}</p><div className="mt-5 flex flex-wrap gap-2"><span className="tag bg-slate-100 text-slate-600"><Clock className="mr-1 h-3 w-3" /> {module.durationMinutes} min</span><span className="tag bg-slate-100 text-slate-600"><BookOpen className="mr-1 h-3 w-3" /> {module.difficulty}</span>{module.score && <span className="tag bg-emerald-50 text-emerald-800">Score {module.score}%</span>}</div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><button className="button-ghost !py-2" onClick={() => window.open('https://atlas.consilio.com', '_blank', 'noopener,noreferrer')}>Open in Atlas <ArrowUpRight className="h-3.5 w-3.5" /></button><button onClick={() => setCompleted(items => isDone ? items.filter(item => item !== module.id) : [...items, module.id])} className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-blue-900">{isDone && <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />}{isDone ? 'Completed' : 'Mark completed'}</button></div></article>; })}</div>
  </div>;
};
const Metric: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="premium-card p-4"><div className="text-2xl font-semibold text-slate-950">{value}</div><div className="mt-1 text-xs font-semibold text-slate-600">{label}</div></div>;
