import React from 'react';
import { AlertTriangle, ArrowRight, ArrowUpRight, Building2, Cpu, Layers3, Sparkles, TrendingDown, Workflow, Wrench } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { DEMO_AI_SEEDED_QUERY } from '../../data/mockData';

export const OverviewView: React.FC = () => {
  const { activeRole, navigateTo, openAiSearch, clients, competitors, tools, workflowStages } = useApp();
  const revenue = clients.reduce((sum, client) => sum + client.annualRevenue, 0);
  const health = Math.round(clients.reduce((sum, client) => sum + client.healthScore, 0) / Math.max(clients.length, 1));
  const risk = clients.filter(client => client.churnRisk === 'High');
  const attention = clients.filter(client => client.status === 'Attention');
  const areas = [
    { title: 'Client intelligence', value: `${risk.length} high-risk`, copy: 'Prioritize single-service exposure and next-best actions.', icon: Building2, tone: 'blue', view: 'client-intelligence' as const },
    { title: 'Market intelligence', value: `${competitors.length} rivals`, copy: 'Read share signals, capability gaps, and competitive moves.', icon: Layers3, tone: 'violet', view: 'competitor-intelligence' as const },
    { title: 'Workflow operating model', value: `${workflowStages.length} stages`, copy: 'Explore the defensible eDiscovery lifecycle and accountability.', icon: Workflow, tone: 'amber', view: 'workflow-roles' as const },
    { title: 'Solution 360', value: `${tools.length} products`, copy: 'Connect tools to people, stages, adoption, and releases.', icon: Wrench, tone: 'emerald', view: 'tools-intelligence' as const },
    { title: 'Technology position', value: '4 rings', copy: 'Move from market context to an actionable capability decision.', icon: Cpu, tone: 'cyan', view: 'technology-intelligence' as const }
  ];
  return <div className="space-y-7">
    <section className="hero-panel relative overflow-hidden rounded-[2rem] p-7 sm:p-10 lg:p-12"><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><div className="relative z-10 max-w-3xl"><div className="eyebrow"><Sparkles className="h-3.5 w-3.5" /> EXECUTIVE SIGNAL DESK</div><h1 className="display-heading mt-5">See the move before it becomes the <em>moment.</em></h1><p className="hero-copy mt-5 max-w-2xl">A single decision surface for the client, market, workflow, solution, and technology signals that matter now.</p><div className="mt-8 flex flex-wrap gap-3"><button className="button-primary" onClick={() => openAiSearch(DEMO_AI_SEEDED_QUERY)}>Ask the Gateway <ArrowUpRight className="h-4 w-4" /></button><button className="button-ghost" onClick={() => navigateTo('client-intelligence')}>Prioritize clients <ArrowRight className="h-4 w-4" /></button></div></div><div className="hero-stat-cluster"><div><strong>{clients.length}</strong><span>Accounts</span></div><div><strong>{risk.length}</strong><span>High-risk</span></div><div><strong>{health}</strong><span>Avg health</span></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Portfolio ARR" value={activeRole === 'New Joiner' ? 'Restricted' : `$${(revenue / 1000000).toFixed(1)}M`} note="Synthetic portfolio signal" /><Metric label="Attention queue" value={`${attention.length}`} note="Accounts need a move" tone="amber" /><Metric label="Solution adoption" value="78.4%" note="Proprietary review engine" tone="green" /><Metric label="Workspace freshness" value="Live" note="Signals synced just now" tone="blue" /></section>
    {activeRole === 'New Joiner' && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mr-2 inline h-4 w-4" /> Management-only portfolio metrics are masked in New Joiner mode.</div>}
    <section><div className="mb-4 flex items-end justify-between"><div><div className="section-kicker">Decision map</div><h2 className="section-title mt-2">Five areas. One <em>operating picture.</em></h2></div><button className="button-ghost" onClick={() => openAiSearch()}>Ask anything <ArrowRight className="h-4 w-4" /></button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{areas.map(area => { const Icon = area.icon; return <button key={area.title} onClick={() => navigateTo(area.view)} className="premium-card group p-6 text-left transition hover:-translate-y-1 hover:border-blue-300"><div className="flex items-start justify-between"><span className={`icon-badge tone-${area.tone}`}><Icon className="h-5 w-5" /></span><ArrowUpRight className="h-5 w-5 text-slate-300 transition group-hover:-translate-y-1 group-hover:text-blue-900" /></div><div className="mt-7 text-xs font-bold uppercase tracking-wider text-slate-400">{area.title}</div><div className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{area.value}</div><p className="mt-2 text-sm leading-6 text-slate-600">{area.copy}</p><div className="mt-6 border-t border-slate-100 pt-4 text-sm font-bold text-blue-900">Open intelligence view <ArrowRight className="ml-1 inline h-4 w-4" /></div></button>; })}</div></section>
    <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="midnight-panel p-7 sm:p-8"><div className="section-kicker section-kicker-light">Priority signal</div><div className="mt-3 flex items-end justify-between gap-4"><div><h2 className="text-3xl font-semibold text-white">{risk[0]?.name || 'Portfolio is stable'}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">{risk[0]?.nextBestAction || 'Keep monitoring health, market position, and workflow quality from the decision map above.'}</p></div><div className="text-right"><div className="text-5xl font-semibold text-white">{risk[0]?.healthScore || health}</div><div className="text-xs uppercase tracking-wider text-white/50">health score</div></div></div><button className="button-light mt-7" onClick={() => navigateTo('client-intelligence')}>Open risk queue <ArrowRight className="h-4 w-4" /></button></div><div className="premium-card p-7"><div className="section-kicker">Signal pulse</div><h2 className="mt-3 text-2xl font-semibold text-slate-950">What changed?</h2><div className="mt-6 space-y-4"><Pulse label="Revenue attention" value={`${attention.length} accounts`} icon={TrendingDown} /><Pulse label="Competitor coverage" value={`${competitors.length} tracked`} icon={Layers3} /><Pulse label="Workflow coverage" value={`${workflowStages.length} delivery stages`} icon={Workflow} /></div></div></section>
  </div>;
};

const Metric: React.FC<{ label: string; value: string; note: string; tone?: string }> = ({ label, value, note, tone = 'slate' }) => <div className="premium-card p-5"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</div><div className={`mt-3 text-3xl font-semibold tracking-tight ${tone === 'amber' ? 'text-amber-700' : tone === 'green' ? 'text-emerald-700' : tone === 'blue' ? 'text-blue-800' : 'text-slate-950'}`}>{value}</div><div className="mt-1 text-sm text-slate-500">{note}</div></div>;
const Pulse: React.FC<{ label: string; value: string; icon: React.ElementType }> = ({ label, value, icon: Icon }) => <div className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-white p-2 text-blue-800 shadow-sm"><Icon className="h-4 w-4" /></span><span className="text-sm font-semibold text-slate-700">{label}</span></div><span className="text-sm font-bold text-slate-950">{value}</span></div>;
