import React, { useMemo, useState } from 'react';
import { ArrowUpRight, BarChart3, Cpu, ExternalLink, Sparkles, TrendingUp } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { TECH_RADAR_ITEMS } from '../../data/mockData';
import { RadarRing } from '../../types';
import { FilterBar, FilterChip, Freshness, HelpButton } from '../ui/PageChrome';

export const TechnologyRadarView: React.FC = () => {
  const { openAiSearch } = useApp();
  const [ring, setRing] = useState<'All' | RadarRing>('All');
  const [category, setCategory] = useState('All');
  const categories = ['All', ...Array.from(new Set(TECH_RADAR_ITEMS.map(item => item.category)))];
  const filtered = useMemo(() => TECH_RADAR_ITEMS.filter(item => (ring === 'All' || item.ring === ring) && (category === 'All' || item.category === category)), [ring, category]);
  const ringTone = (value: RadarRing) => value === 'Adopt' ? 'bg-emerald-50 text-emerald-800 border-emerald-200' : value === 'Trial' ? 'bg-blue-50 text-blue-800 border-blue-200' : value === 'Assess' ? 'bg-amber-50 text-amber-800 border-amber-200' : 'bg-rose-50 text-rose-800 border-rose-200';

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 border-b border-slate-200/70 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow"><Cpu className="h-3.5 w-3.5" /> Intelligence 03</div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">Technology <span className="font-serif italic font-normal text-blue-950">position.</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">A focused view of Consilio’s technology posture, market context, and the capability signals shaping modern eDiscovery.</p></div><div className="flex items-center gap-2"><HelpButton title="How to read Technology" body="Start with the market benchmark, then filter the capability map by maturity and ring. Open a signal for its operational impact and evidence." /><button className="button-ghost" onClick={() => openAiSearch('What technologies are currently in the Trial and Assess rings?')}><Sparkles className="h-3.5 w-3.5" /> Ask the Gateway</button></div></div>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BarChart3} label="Global eDiscovery benchmark" value="$14.8B" note="2025 public estimate" tone="blue" /><Metric icon={TrendingUp} label="North America share" value="39%" note="Regional benchmark" tone="green" /><Metric icon={Cpu} label="Signals mapped" value={`${TECH_RADAR_ITEMS.length}`} note="Across 4 maturity rings" tone="purple" /><Metric icon={Sparkles} label="Consilio vendor share" value="—" note="Not publicly disclosed" tone="slate" /></div>

    <FilterBar label="Technology signal filters" count={filtered.length} onReset={() => { setRing('All'); setCategory('All'); }}><div className="flex flex-wrap gap-2">{(['All', 'Adopt', 'Trial', 'Assess', 'Hold'] as const).map(value => <FilterChip key={value} active={ring === value} onClick={() => setRing(value)}>{value}</FilterChip>)}</div><select value={category} onChange={event => setCategory(event.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-semibold text-slate-700 outline-none focus:border-blue-800">{categories.map(item => <option key={item}>{item}</option>)}</select></FilterBar>

    <section className="premium-card overflow-hidden"><div className="grid gap-8 p-6 lg:grid-cols-[.85fr_1.15fr] lg:p-8"><div><div className="section-kicker">Position map</div><h2 className="section-title mt-3">From market <em>context</em> to action.</h2><p className="mt-4 text-sm leading-7 text-slate-600">Public data supports market-level and regional benchmarks. Consilio-specific vendor share remains intentionally unreported until an approved denominator is available.</p><div className="mt-6 space-y-3"><Legend color="bg-emerald-500" label="Adopt" copy="Production standard" /><Legend color="bg-blue-500" label="Trial" copy="Active pilot" /><Legend color="bg-amber-500" label="Assess" copy="Strategic evaluation" /><Legend color="bg-rose-500" label="Hold" copy="Retire or avoid" /></div><a className="source-link mt-7" href="https://www.cascadiacapital.com/wp-content/uploads/Cascadia-Legal-Compliance-Tech-Industry-Report-2024.pdf" target="_blank" rel="noreferrer">Open market benchmark <ExternalLink className="h-3 w-3" /></a></div><div className="technology-orbit"><div className="orbit orbit-outer" /><div className="orbit orbit-middle" /><div className="orbit orbit-inner" /><div className="orbit-center"><Cpu className="h-7 w-7" /><span>Consilio<br />capability</span></div><span className="orbit-label orbit-label-one">AI & ML</span><span className="orbit-label orbit-label-two">Cloud</span><span className="orbit-label orbit-label-three">Privacy</span><span className="orbit-label orbit-label-four">ECA</span></div></div></section>

    <section className="grid gap-4 md:grid-cols-2">{filtered.map(item => <article key={item.id} className="premium-card group p-5 transition hover:-translate-y-1 hover:border-blue-200"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2 py-0.5 text-[10px] font-bold ${ringTone(item.ring)}`}>{item.ring}</span><Freshness label="Evidence refreshed" /></div><h3 className="mt-3 text-base font-semibold text-slate-950">{item.name}</h3></div><ArrowUpRight className="h-4 w-4 text-slate-300 transition group-hover:-translate-y-0.5 group-hover:text-blue-900" /></div><div className="mt-3 flex flex-wrap gap-1.5"><span className="tag tag-blue">{item.category}</span><span className="tag bg-slate-100 text-slate-600">Maturity · {item.consilioMaturity}</span><span className="tag bg-slate-100 text-slate-600">Market adoption · {item.marketAdoptionPct}%</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{item.summary}</p><div className="mt-4 border-t border-slate-100 pt-3 text-xs leading-5 text-slate-600"><strong className="text-slate-900">Decision signal:</strong> {item.impactOnRoles}</div></article>)}</section>
  </div>;
};

const Metric: React.FC<{ icon: React.ElementType; label: string; value: string; note: string; tone: string }> = ({ icon: Icon, label, value, note, tone }) => <div className="premium-card p-4"><div className="flex items-center justify-between"><span className={`rounded-lg p-2 ${tone === 'blue' ? 'bg-blue-50 text-blue-900' : tone === 'green' ? 'bg-emerald-50 text-emerald-800' : tone === 'purple' ? 'bg-violet-50 text-violet-800' : 'bg-slate-100 text-slate-700'}`}><Icon className="h-4 w-4" /></span><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">P1</span></div><div className="mt-5 text-2xl font-semibold tracking-tight text-slate-950">{value}</div><div className="mt-1 text-xs font-semibold text-slate-700">{label}</div><div className="mt-1 text-[11px] text-slate-500">{note}</div></div>;
const Legend: React.FC<{ color: string; label: string; copy: string }> = ({ color, label, copy }) => <div className="flex items-center gap-3 text-xs"><span className={`h-2 w-2 rounded-full ${color}`} /><span className="font-bold text-slate-800">{label}</span><span className="text-slate-500">{copy}</span></div>;
