import React, { useMemo, useState } from 'react';
import { ArrowUpRight, Bookmark, CheckCircle2, ExternalLink, Layers, Search, Sparkles, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { DataFreshnessBanner, FilterBar, FilterChip, Freshness, HelpButton } from '../ui/PageChrome';

export const ToolsIntelligenceView: React.FC = () => {
  const { tools, selectedToolId, openAiSearch } = useApp();
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState(selectedToolId || 'consilio-sightline');
  const [category, setCategory] = useState('All');
  const categories = ['All', 'Review', 'Processing', 'Forensics'];
  const filtered = useMemo(() => tools.filter(tool => {
    const matchesQuery = `${tool.name} ${tool.category} ${tool.whatItDoes}`.toLowerCase().includes(query.toLowerCase());
    const matchesCategory = category === 'All' || tool.category.toLowerCase().includes(category.toLowerCase());
    return matchesQuery && matchesCategory;
  }), [tools, query, category]);
  const activeTool = tools.find(tool => tool.id === selectedId) || filtered[0] || tools[0];

  return <div className="space-y-7">
    <DataFreshnessBanner source="Solution and product catalog" age="Updated today" />
    <section className="hero-panel overflow-hidden rounded-[2rem] p-7 sm:p-10">
      <div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" />
      <div className="relative z-10 flex flex-col justify-between gap-7 lg:flex-row lg:items-end">
        <div><div className="eyebrow"><Sparkles className="h-3.5 w-3.5" /> INTELLIGENCE AREA 04 · SOLUTION 360</div><h1 className="display-heading mt-4">Product Atlas for the <em>whole matter.</em></h1><p className="hero-copy mt-4 max-w-2xl">A connected catalog of products, operating stages, adoption signals, and assigned teams. Select a capability to expand its full operating profile.</p></div>
        <div className="flex flex-wrap gap-2"><HelpButton title="How to read Product Atlas" body="Choose a product card to open its workflow coverage, users, deployment tier, and latest release notes." /><button className="button-light" onClick={() => openAiSearch('What tools are used during review?')}><Sparkles className="h-4 w-4" /> Ask the Gateway</button></div>
      </div>
      <div className="relative z-10 mt-8 grid gap-3 sm:grid-cols-4">{[['Solutions', tools.length], ['Avg adoption', `${Math.round(tools.reduce((sum, t) => sum + t.adoptionRatePct, 0) / Math.max(tools.length, 1))}%`], ['Operational', tools.filter(t => t.systemStatus === 'Operational').length], ['Workflow links', tools.reduce((sum, t) => sum + t.workflowStages.length, 0)]].map(([label, value]) => <div key={label as string} className="hero-stat"><strong>{value as string}</strong><span>{label as string}</span></div>)}</div>
    </section>
    <FilterBar label="Product Atlas filters" count={filtered.length} onReset={() => { setQuery(''); setCategory('All'); }}><FilterChip active={category === 'All'} onClick={() => setCategory('All')}>All products</FilterChip>{categories.slice(1).map(item => <FilterChip key={item} active={category === item} onClick={() => setCategory(item)}>{item}</FilterChip>)}<Freshness label="Catalog updated today" /></FilterBar>
    <div className="relative"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by product, capability, or workflow stage…" className="w-full rounded-2xl border border-slate-200 bg-white px-12 py-4 text-base text-slate-900 shadow-sm outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-100" /></div>
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(tool => <button key={tool.id} onClick={() => setSelectedId(tool.id)} className={`text-left premium-card group p-6 transition hover:-translate-y-1 ${activeTool?.id === tool.id ? 'border-blue-400 bg-blue-50/40 ring-2 ring-blue-100' : ''}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="tag tag-blue">{tool.category}</span>{tool.systemStatus === 'Operational' && <span className="text-[10px] font-bold text-emerald-700"><CheckCircle2 className="mr-1 inline h-3 w-3" />Live</span>}</div><h2 className="mt-4 text-xl font-semibold text-slate-950">{tool.name}</h2><p className="mt-1 text-sm font-medium text-blue-900">{tool.tagline}</p></div><ArrowUpRight className="h-5 w-5 text-slate-300 transition group-hover:-translate-y-1 group-hover:text-blue-900" /></div><p className="mt-5 line-clamp-3 text-sm leading-6 text-slate-600">{tool.whatItDoes}</p><div className="mt-6 flex items-end justify-between border-t border-slate-100 pt-4"><div><div className="text-3xl font-semibold tracking-tight text-slate-950">{tool.adoptionRatePct}%</div><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">fleet adoption</div></div><div className="text-right text-xs text-slate-500"><div>{tool.workflowStages.length} workflow links</div><div className="mt-1 text-blue-800">Inspect profile →</div></div></div></button>)}</section>
    {activeTool && <section className="premium-card overflow-hidden border-blue-200"><div className="flex flex-col gap-5 border-b border-slate-100 bg-gradient-to-r from-white to-blue-50/60 p-7 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="tag tag-blue">Selected capability</span><Freshness label="Evidence current" /></div><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{activeTool.name}</h2><p className="mt-2 max-w-3xl text-base leading-7 text-slate-600">{activeTool.whatItDoes}</p></div><a href={activeTool.atlasDocUrl} target="_blank" rel="noreferrer" className="button-primary shrink-0"><Bookmark className="h-4 w-4" /> Open in Atlas <ExternalLink className="h-3.5 w-3.5" /></a></div><div className="grid gap-4 p-7 md:grid-cols-2 xl:grid-cols-4"><div className="detail-tile"><Users className="h-5 w-5 text-blue-700" /><strong>Assigned roles</strong><div>{activeTool.whoUsesIt.join(' · ')}</div></div><div className="detail-tile"><Layers className="h-5 w-5 text-emerald-700" /><strong>Workflow stages</strong><div>{activeTool.workflowStages.join(' · ')}</div></div><div className="detail-tile"><strong>Deployment tier</strong><div>{activeTool.adoptionTier} · {activeTool.adoptionRatePct}% active matters</div></div><div className="detail-tile"><strong>Licensing model</strong><div>{activeTool.licenseModel}</div></div></div><div className="grid gap-3 border-t border-slate-100 p-7 md:grid-cols-2">{activeTool.recentReleases.map(release => <div key={release.version} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex justify-between text-sm font-bold text-slate-900"><span>{release.version}</span><span className="text-xs font-medium text-slate-400">{release.date}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{release.note}</p></div>)}</div></section>}
  </div>;
};
